name: Download Asset

on:
  workflow_dispatch:
  release:
    types: ["released"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: Get URL
        id: get_url
        uses: actions/github-script@v7
        with:
          script: |
            const assets = github.event.release.assets;
            const url = assets.find(a => startsWith(a.name, 'test-') && endsWith(a.name, '.tar.gz')).url;
            core.setOutput('url', url);
      - name: Check URL
        env:
          URL: ${{ steps.get_url.outputs.url }}
        run: echo $URL
