name: Download Asset

on:
  workflow_dispatch:
  release:
    types: ["released"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get URL
        id: get_url
        uses: actions/github-script@v7
        with:
          script: |
            const rel = await(github.event.release);
            const url = rel.assets.find(a => startsWith(a.name, 'test-') && endsWith(a.name, '.tar.gz')).url;
            core.setOutput('url', url);
      - name: Check URL
        env:
          URL: ${{ steps.get_url.outputs.url }}
        run: echo $URL
