name: Download Asset

on:
  workflow_dispatch:
  release:
    types: ["created", "edited", "published"]

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: Get URL
        id: get_url
        uses: actions/github-script@v7
        with:
          debug: true
          script: |
            const assets = github.event.release.assets;
            const docs = assets.find(a => startsWith(a.name, 'test-'));
            core.setOutput('url', docs.browser_download_url);
      - name: Check URL
        env:
          URL: ${{ steps.get_url.outputs.url }}
        run: echo $URL
