name: Download Asset

on:
  release:

# concurrency:
#   group: ${{ github.ref_name }}-${{ github.workflow_ref }}
#   cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: Check Assets
        id: docs-check
        uses: actions/github-script@v7
        with:
          debug: true
          script: |
            return github.event.release.assets.contains((a) => startsWith(a.name, "test-"))
      - name: Get URL
        id: docs-url
        if: false
        uses: actions/github-script@v7
        with:
          debug: true
          script: |
            const assets = github.event.release.assets;
            const docs = assets.find(a => startsWith(a.name, 'test-'));
            core.setOutput('url', docs.browser_download_url);
      - name: Check URL
        if: false
        env:
          URL: ${{ steps.docs-url.outputs.url }}
        run: echo $URL
