name: Main

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > test.txt
      - name: Test
        run: cat test.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: test.txt
