name: Main

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p test/a test/b
          cd test
          echo "test a ${{ github.sha }}" > a/test.txt
          echo "test b ${{ github.sha }}" > b/test.txt
      - name: Test
        run: head test/*/*
      - name: Compress
        working-directory: test
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          tar -czf ../test-${TAG_NAME}.tar.gz a b
          zip -rq ../test-${TAG_NAME}.zip a b
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            test-${{ github.ref_name }}.tar.gz
            test-${{ github.ref_name }}.zip
