name: Main

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p test/a test/b
          echo "test a ${{ github.sha }}" > test/a/test.txt
          echo "test b ${{ github.sha }}" > test/b/test.txt
      - name: Test
        run: head test/*/*
      - name: Compress
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          tar czf test/a test/b -o test-${TAG_NAME}.tar.gz
          zip -rq test-${TAG_NAME}.zip test/a test/b
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            test-v*.tar.gz
            test-v*.zip
