name: Main

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir a b
          echo "a${{ github.sha }}" > a/test.txt
          echo "b${{ github.sha }}" > b/test.txt
      - name: Test
        run: head */test.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            a/test.txt
            b/test.txt
